name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Check formatting
        run: lune run ./Submodules/luau-cicd/Scripts/CheckFormatting.luau

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Install dependencies
        run: wally install

      - name: Run tests
        run: lune run ./Scripts/RunTests.luau

  analyze:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Install dependencies
        run: wally install

      - name: Setup Lune typedefs
        run: lune setup --no-update-luaurc

      - name: Run static analysis
        run: lune run ./Submodules/luau-cicd/Scripts/RunStaticAnalysis.luau

  changelog:
    name: Check changelog format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Check changelog format
        run: lune run ./Submodules/luau-cicd/Scripts/CheckChangelogFormat.luau

  rokit-format:
    name: Check rokit.toml format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Check rokit.toml format
        run: lune run ./Submodules/luau-cicd/Scripts/CheckRokitFormat.luau

  wally-format:
    name: Check wally.toml format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Check wally.toml format
        run: lune run ./Submodules/luau-cicd/Scripts/CheckWallyFormat.luau

  file-headers:
    name: Check file headers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Check file headers
        run: lune run ./Submodules/luau-cicd/Scripts/CheckFileHeaders.luau

  luaurc-format:
    name: Check .luaurc format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Check .luaurc format
        run: lune run ./Submodules/luau-cicd/Scripts/CheckLuaurcFormat.luau

  no-tabs:
    name: Check for tabs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Check for tabs
        run: lune run ./Submodules/luau-cicd/Scripts/CheckNoTabs.luau
